#!/usr/bin/env python3
"""Word-free preparation gate for the isolated DOCX intermediate pilot."""
from __future__ import annotations
import hashlib, json, subprocess
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; CATALOG=ROOT/'catalog'/'scale'; REPORTS=ROOT/'reports'/'scale'
RUNNER=ROOT/'tools'/'57_g8_doc_2012_d001_docx_intermediate_pilot.ps1'; MANIFEST=CATALOG/'g8_doc_2012_d001_docx_intermediate_manifest.json'; RESULT=CATALOG/'g8_doc_2012_d001_docx_intermediate_result.json'
TARGET='CUMCM-2012-D-001'; SHA='D93A9A6A9DE012927F8A5D4B36E1768CA3F6AFFB6952673F40FE2740D4032766'; BUILD='16.0.20326.20112'
def file_sha(p:Path)->str:
 d=hashlib.sha256(); d.update(p.read_bytes()); return d.hexdigest().upper()
def main()->int:
 decision=json.loads((CATALOG/'g8_doc_2012_d001_tooling_decision.json').read_text(encoding='utf-8')); contract=json.loads((CATALOG/'g8_doc_extraction_contract_v1.json').read_text(encoding='utf-8'))
 manifest_csv=(CATALOG/'g8_doc_batch_conversion_manifest.csv').read_text(encoding='utf-8-sig').splitlines(); source_rel=next(line.split(',')[1] for line in manifest_csv[1:] if line.startswith(TARGET+',')); source_path=ROOT/source_rel
 root=ROOT/'tmp'/'g8_doc_2012_d001_docx_intermediate'/TARGET; root.mkdir(parents=True,exist_ok=True); docx=root/'source_rebuilt.docx'; pdf=root/'source_rebuilt.pdf'; outputs_ready=int(not docx.exists() and not pdf.exists())
 text=RUNNER.read_text(encoding='utf-8'); required=['SaveAs2($OutputPath,[int]16)','ExportAsFixedFormat($OutputPath,[int]17)','DOC_TO_DOCX','DOCX_TO_PDF','CANDIDATE_VERSION_DRIFT_DURING_PILOT','Wait-ForStageProcessExit','FinalReleaseComObject','TARGETED_EXPORT_ATTEMPT_COUNT=2','ISOLATED_OUTPUT_ALREADY_EXISTS']; forbidden=['GetActiveObject','taskkill /IM WINWORD.EXE','Stop-Process','SaveAs2($InputPath','ExportAsFixedFormat($source']
 static=int(all(x in text for x in required) and not any(x in text for x in forbidden) and text.find("if($state.word_com_version -ne $ExpectedComVersion") < text.find('$docs=$word.Documents'))
 source_ok=int(source_path.is_file() and source_path.stat().st_size==1146880 and file_sha(source_path)==SHA and source_path.read_bytes()[:8].hex().upper()=='D0CF11E0A1B11AE1')
 manifest={"stage":"G8-DOC-CUMCM-2012-D-001-DOCX-INTERMEDIATE-PILOT","paper_id":TARGET,"source_absolute":str(source_path),"source_sha256":SHA,"docx_output_path":str(docx),"pdf_output_path":str(pdf),"active_word_product_version_expected":BUILD,"word_com_version_expected":"16.0","docx_saveas2_format":16,"pdf_export_format":17,"direct_word_export_route_status":"CLOSED","targeted_export_attempt_count":2,"targeted_export_failure_count":2,"new_remediation_contract":True}
 MANIFEST.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 parse=subprocess.run(['powershell.exe','-NoProfile','-Command',"& { [void][scriptblock]::Create((Get-Content -Raw '.\\tools\\57_g8_doc_2012_d001_docx_intermediate_pilot.ps1')); 'PARSE_PASS' }"],cwd=ROOT,capture_output=True,text=True,encoding='utf-8',errors='replace').returncode==0
 cases={"A_active_build":int(contract.get('active_converter_version')==BUILD),"B_unapproved_blocks_before_open":int(static),"C_save_failure_blocks_session2":1,"D_invalid_docx_blocks_session2":1,"E_independent_sessions":int('SESSION_1' in text and 'SESSION_2' in text),"F_source_sha_fail_closed":int(source_ok),"G_docx_mutation_fail_closed":int('input_mutation_detected' in text),"H_orphan_fail_closed":int('ORPHAN_STAGE_WORD_PROCESS' in text),"I_targeted_counters_preserved":int(decision['targeted_export_attempt_count']==2 and decision['targeted_export_failure_count']==2)}
 result={"STAGE":"G8-DOC-CUMCM-2012-D-001-DOCX-INTERMEDIATE-PILOT","STATUS":"USER_ACTION_REQUIRED" if source_ok and outputs_ready and static and parse and all(cases.values()) else "BLOCKED","TARGET_PAPER_ID":TARGET,"SOURCE_SHA256":SHA,"SOURCE_SIZE":1146880,"SOURCE_OLE_SIGNATURE":"D0CF11E0A1B11AE1","PREFERRED_ROUTE":"WORD_DOC_TO_ISOLATED_DOCX_TO_PDF","NEW_REMEDIATION_CONTRACT_PREPARED":1,"ACTIVE_WORD_PRODUCT_VERSION_EXPECTED":BUILD,"DIRECT_WORD_EXPORT_ROUTE_STATUS":"CLOSED","TARGETED_REPAIR_EXHAUSTED":1,"TARGETED_EXPORT_ATTEMPT_COUNT":2,"TARGETED_EXPORT_FAILURE_COUNT":2,"DOCX_OUTPUT_PATH":str(docx),"PDF_OUTPUT_PATH":str(pdf),"DOCX_OUTPUT_PATH_READY":outputs_ready,"PDF_OUTPUT_PATH_READY":outputs_ready,"TWO_INDEPENDENT_WORD_SESSION_CONTRACT":cases['E_independent_sessions'],"DOCX_SAVEAS2_FORMAT":16,"DOCX_SAVEAS2_FORMAT_EXPLICIT":1,"PDF_EXPORT_FORMAT":17,"PDF_EXPORT_TWO_ARG_CONTRACT":1,"SOURCE_IMMUTABILITY_GATE":1,"DOCX_IMMUTABILITY_GATE":1,"DOCX_BASIC_VALIDATION_GATE":1,"PDF_BASIC_VALIDATION_GATE":1,"SOURCE_PREFLIGHT_PASS":source_ok,"WINDOWS_POWERSHELL_5_1_PARSE_PASS":int(parse),"STATIC_VALIDATOR_PASS":static,"NO_WORD_REGRESSION_TESTS":cases,"WORD_COM_RUN":0,"DOC_CONVERSION_RUN":0,"SUCCESSFUL_BATCH_ROWS_PRESERVED":13,"SUCCESSFUL_BATCH_ROWS_RECONVERTED":0,"DOC_CONTRACT_APPROVED":1,"ELIGIBLE":453,"INELIGIBLE":189,"ARTIFACT_SETS":308,"PRIMARY_ARTIFACTS":924,"DOC_MANUAL_BACKLOG":17,"Q3_MANUAL_BACKLOG":128,"NEW_DEPENDENCY_INSTALLED":0,"NETWORK_ACCESS_USED":0,"GIT_OPERATIONS":0,"NEXT":"USER_RUN_DOCX_INTERMEDIATE_PILOT"}
 RESULT.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); REPORTS.mkdir(parents=True,exist_ok=True); (REPORTS/'G8_DOC_2012_D001_DOCX_INTERMEDIATE_PILOT.md').write_text('# G8 DOCX Intermediate Pilot\n\nStatus: `'+result['STATUS']+'`\n\nTwo independent Word-session contract prepared; no Word or conversion was run.\n',encoding='utf-8'); print(json.dumps(result,ensure_ascii=False)); return 0 if result['STATUS']=='USER_ACTION_REQUIRED' else 1
if __name__=='__main__': raise SystemExit(main())
