#!/usr/bin/env python3
"""Prepare, but never execute, external reacquisition for one logical paper."""
from __future__ import annotations
import csv, json, re, zipfile, xml.etree.ElementTree as ET
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; CATALOG=ROOT/'catalog'/'scale'; REPORTS=ROOT/'reports'/'scale'; TARGET='CUMCM-2012-D-001'; DOCX=ROOT/'tmp/g8_doc_2012_d001_docx_intermediate/CUMCM-2012-D-001/source_rebuilt.docx'
def docx_text():
 with zipfile.ZipFile(DOCX) as z: root=ET.fromstring(z.read('word/document.xml'))
 ns={'w':'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}; rows=[''.join(x.text or '' for x in p.findall('.//w:t',ns)).strip() for p in root.findall('.//w:p',ns)]
 return [re.sub(r'\s+',' ',x) for x in rows if x]
def main():
 decision=json.loads((CATALOG/'g8_doc_2012_d001_reacquisition_decision.json').read_text(encoding='utf-8')); paragraphs=docx_text(); body=' '.join(paragraphs)
 snippets=[]
 for paragraph in paragraphs:
  if len(paragraph)>=20 and len(snippets)<6:
   snippets.append(paragraph[:100])
 fingerprint={'logical_identity':TARGET,'source_evidence':'isolated derivative DOCX; not an authoritative replacement','title':'UNAVAILABLE','authors':'UNAVAILABLE','abstract_prefix':'UNAVAILABLE','keywords':'UNAVAILABLE','section_headings':'UNAVAILABLE','table_captions':'UNAVAILABLE','figure_captions':'UNAVAILABLE','reference_snippets':'UNAVAILABLE','distinctive_text_snippets':snippets,'text_extraction_note':'OOXML w:t text is a future identity aid only; it is not a semantic-equivalence verdict.'}
 # Do not guess title/authors from a filename.  Only use safely bounded snippets.
 queries=[
  {'query_id':'Q1','query':'"CUMCM 2012 D 优秀论文"','purpose':'broad competition archive discovery','uses_d044':0},
  {'query_id':'Q2','query':'"2012 数学建模 D题 优秀论文"','purpose':'higher-education archive discovery','uses_d044':0},
  {'query_id':'Q3','query':'"机器人避障 2012 数学建模 优秀论文"','purpose':'problem-title constrained discovery','uses_d044':0},
 ]
 if snippets: queries.append({'query_id':'Q4','query':'"'+snippets[0][:50]+'"','purpose':'distinctive-text verification search','uses_d044':0})
 contract={'stage':'G8-DOC-CUMCM-2012-D-001-EXTERNAL-REACQUISITION-DECISION','logical_identity':TARGET,'network_authorization_required':True,'download_root':'tmp/g8_doc_2012_d001_external_reacquisition/{candidate_id}/','allowed_download_extensions':['.pdf','.doc','.docx'],'prohibited_download_extensions':['.exe','.msi','.js','.scr','.bat','.cmd','.ps1'],'max_first_round_candidate_urls':10,'source_trust_hierarchy':{'tier_1':['official CUMCM/competition archive','officially affiliated site','author or adviser university official domain'],'tier_2':['university resource repository','university teacher page','stable educational archive'],'tier_3':['personal blog','forum attachment','unverified file-sharing or repost']},'identity_classes':['EXACT_IDENTITY_CONFIRMED','HIGH_CONFIDENCE_SAME_PAPER','LIKELY_SAME_PAPER','AMBIGUOUS','DIFFERENT_PAPER'],'exact_identity_rule':'Require multiple independent features: title/authors when available, abstract, section sequence, distinctive text, tables/figures, and references. Filename/problem/year alone is insufficient.','provenance_required':['candidate_id','source_url','source_domain','source_tier','retrieved_at','filename','format','size','sha256','http_content_type','http_last_modified','http_etag','identity_status','identity_evidence'],'pdf_acceptance_gate':['readable non-encrypted PDF','positive page count','no unexplained pages','page accounting match','content sanity pass','identity verification pass','complete provenance'],'relationship_on_acceptance':'REACQUIRED_ALTERNATE_SOURCE; original DOC remains immutable','no_automatic_artifact_promotion':True,'network_behavior':'Only a separately user-authorized next stage may search public pages or download candidates.'}
 (CATALOG/'g8_doc_2012_d001_identity_fingerprint.json').write_text(json.dumps(fingerprint,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); (CATALOG/'g8_doc_2012_d001_external_reacquisition_contract.json').write_text(json.dumps(contract,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 with (CATALOG/'g8_doc_2012_d001_external_search_queries.csv').open('w',encoding='utf-8',newline='') as f:w=csv.DictWriter(f,fieldnames=['query_id','query','purpose','uses_d044']);w.writeheader();w.writerows(queries)
 summary={'stage':'G8-DOC-CUMCM-2012-D-001-EXTERNAL-REACQUISITION-DECISION','status':'PASS','target_paper_id':TARGET,'source_sha256':decision['source_sha256'],'source_size':decision['source_size'],'external_reacquisition_required':1,'external_reacquisition_contract_prepared':1,'derivative_docx_available':1,'derivative_docx_sha256':'B948CA41387ABC408724B1D64286830B54B12198A33C54D8BE684661CA8937DC','identity_fingerprint_prepared':1,'identity_fingerprint_field_count':len(fingerprint),'title':'UNAVAILABLE','authors':'UNAVAILABLE','keywords':'UNAVAILABLE','distinctive_text_snippet_count':len(snippets),'source_trust_hierarchy_defined':1,'external_identity_classification_defined':1,'external_download_isolation_defined':1,'provenance_contract_defined':1,'external_pdf_acceptance_gate_defined':1,'search_query_plan_prepared':1,'search_query_count':len(queries),'max_first_round_candidate_urls':10,'d044_used_as_target_identity_key':0,'network_access_used':0,'download_run':0,'direct_word_export_route_status':'CLOSED','docx_intermediate_route_status':'CLOSED','successful_batch_rows_preserved':13,'successful_batch_rows_reconverted':0,'doc_contract_approved':1,'eligible':453,'ineligible':189,'artifact_sets':308,'primary_artifacts':924,'doc_manual_backlog':17,'q3_manual_backlog':128,'word_com_run':0,'doc_conversion_run':0,'source_sha_mismatch':0,'original_files_modified':0,'new_dependency_installed':0,'git_operations':0,'next':'G8-DOC-CUMCM-2012-D-001-EXTERNAL-REACQUISITION'}
 REPORTS.mkdir(parents=True,exist_ok=True);(REPORTS/'G8_DOC_2012_D001_EXTERNAL_REACQUISITION_DECISION.md').write_text('# G8 DOC External Reacquisition Decision\n\nStatus: `PASS`\n\nContract, bounded query plan, and identity fingerprint were prepared without network access. External searching and download remain separately user-authorized.\n',encoding='utf-8');print(json.dumps(summary,ensure_ascii=False));return 0
if __name__=='__main__':raise SystemExit(main())
